[package]
name = "panoptes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "3", features = ["derive"]}
git2 = "0.13"
walkdir = "2"
rusqlite = { version = "0.27.0", features = ["bundled"] }
ansi-escapes = "0.1.1"
colored = "2.0.0"
chrono = "0.4"